CREATE TABLE t1(a int, b int)$$

CREATE LUA TRIGGER t1_audit ON (table t1 FOR INSERT AND UPDATE AND DELETE) AUDITED

CREATE LUA TRIGGER t1_audit ON (table t1 FOR INSERT AND UPDATE AND DELETE) AUDITED

DROP LUA TRIGGER t1_audit

CREATE LUA TRIGGER t1_audit ON (table t1 FOR INSERT AND UPDATE AND DELETE) AUDITED

DROP TABLE '$audit_t1'

CREATE LUA TRIGGER shoutout_to_alexw ON (table t1 FOR INSERT AND UPDATE AND DELETE) AUDITED

SELECT * FROM comdb2_tables

DROP LUA TRIGGER t1_audit
DROP LUA TRIGGER shoutout_to_alexw 
DROP TABLE '$audit_t1'
DROP TABLE '$audit_t1$2'
DROP TABLE t1